/**
 * Global Sovereign Nations Offline Encyclopedia
 * Standard UN recognition baseline + common international aliases.
 */
const COUNTRY_DATASET = [
  // A
  { name: "Afghanistan", continent: "Asia", capital: "Kabul", language: "Pashto / Dari", greeting: "Salam", greetingTranslation: "Peace be with you", flagEmoji: "🇦🇫", funFact: "Home to ancient lapis lazuli mines that have supplied the world for over 6,000 years.", characterStyle: "central-asia" },
  { name: "Albania", continent: "Europe", capital: "Tirana", language: "Albanian", greeting: "Përshëndetje", greetingTranslation: "Hello", flagEmoji: "🇦🇱", funFact: "Known for its unique mountain eagles and thousands of historic concrete bunkers.", characterStyle: "balkan" },
  { name: "Algeria", continent: "Africa", capital: "Algiers", language: "Arabic / Berber", greeting: "Salam", greetingTranslation: "Peace", flagEmoji: "🇩🇿", funFact: "The largest nation by geographic landmass on the African continent.", characterStyle: "north-africa" },
  { name: "Andorra", continent: "Europe", capital: "Andorra la Vella", language: "Catalan", greeting: "Hola", greetingTranslation: "Hello", flagEmoji: "🇦🇩", funFact: "A scenic microstate nestled in the Pyrenees peaks, co-governed by two foreign princes.", characterStyle: "european" },
  { name: "Angola", continent: "Africa", capital: "Luanda", language: "Portuguese", greeting: "Olá", greetingTranslation: "Hello", flagEmoji: "🇦🇴", funFact: "Giant sable antelopes, previously feared extinct, were rediscovered roaming its plains.", characterStyle: "african" },
  { name: "Antigua and Barbuda", continent: "North America", capital: "St. John's", language: "English", greeting: "Hello", greetingTranslation: "Hello", flagEmoji: "🇦🇬", funFact: "Legend holds that the island nation offers exactly 365 beaches—one for every day of the year.", characterStyle: "caribbean", aliases: ["antigua", "barbuda"] },
  { name: "Argentina", continent: "South America", capital: "Buenos Aires", language: "Spanish", greeting: "¡Hola!", greetingTranslation: "Hello!", flagEmoji: "🇦🇷", funFact: "Birthplace of the tango dance and home to the majestic peaks of Aconcagua.", characterStyle: "latino" },
  { name: "Armenia", continent: "Asia", capital: "Yerevan", language: "Armenian", greeting: "Barev", greetingTranslation: "Life to you", flagEmoji: "🇦🇲", funFact: "Its vibrant pink-tuff capital Yerevan is older than Rome by nearly three decades.", characterStyle: "caucasus" },
  { name: "Australia", continent: "Oceania", capital: "Canberra", language: "English", greeting: "G'day!", greetingTranslation: "Good day!", flagEmoji: "🇦🇺", funFact: "Home to the world's largest living organism structure: the Great Barrier Reef.", characterStyle: "oceanian", aliases: ["aussie", "oz"] },
  { name: "Austria", continent: "Europe", capital: "Vienna", language: "German", greeting: "Servus", greetingTranslation: "At your service", flagEmoji: "🇦🇹", funFact: "Composed predominantly of alpine terrain, it pioneered classical orchestral mastery.", characterStyle: "alpine" },
  { name: "Azerbaijan", continent: "Asia", capital: "Baku", language: "Azerbaijani", greeting: "Salam", greetingTranslation: "Peace", flagEmoji: "🇦🇿", funFact: "Nicknamed 'The Land of Fire' for natural subterranean natural gas flames that never extinguish.", characterStyle: "caucasus" },

  // B
  { name: "Bahamas", continent: "North America", capital: "Nassau", language: "English", greeting: "Hello", greetingTranslation: "Hello", flagEmoji: "🇧🇸", funFact: "Resting upon limestone reef shelves with famously clear oceanic waters.", characterStyle: "caribbean", aliases: ["the bahamas"] },
  { name: "Bahrain", continent: "Asia", capital: "Manama", language: "Arabic", greeting: "Marhaba", greetingTranslation: "Welcome", flagEmoji: "🇧🇭", funFact: "A vibrant archipelago kingdom in the Persian Gulf renowned for natural pearl diving.", characterStyle: "middle-east" },
  { name: "Bangladesh", continent: "Asia", capital: "Dhaka", language: "Bengali", greeting: "Nomoshkar", greetingTranslation: "Greetings", flagEmoji: "🇧🇩", funFact: "Houses the Sundarbans, the planet's vastest continuous mangrove delta jungle.", characterStyle: "south-asia" },
  { name: "Barbados", continent: "North America", capital: "Bridgetown", language: "English", greeting: "Howdy!", greetingTranslation: "Greetings!", flagEmoji: "🇧🇧", funFact: "The historic birthplace of spiced sugar-cane spirits and flying fish cuisine.", characterStyle: "caribbean" },
  { name: "Belarus", continent: "Europe", capital: "Minsk", language: "Belarusian / Russian", greeting: "Pryvitannie", greetingTranslation: "Welcome", flagEmoji: "🇧🇾", funFact: "Features the Belovezhskaya Pushcha, preserving ancient primeval European woodland.", characterStyle: "slavic" },
  { name: "Belgium", continent: "Europe", capital: "Brussels", language: "Dutch / French / German", greeting: "Hallo", greetingTranslation: "Hello", flagEmoji: "🇧🇪", funFact: "Produces over 2,000 artisan chocolate varieties and hosts key European Union assemblies.", characterStyle: "european" },
  { name: "Belize", continent: "North America", capital: "Belmopan", language: "English", greeting: "Hello", greetingTranslation: "Hello", flagEmoji: "🇧🇿", funFact: "Home to the Great Blue Hole, an immense oceanic marine sinkhole.", characterStyle: "caribbean" },
  { name: "Benin", continent: "Africa", capital: "Porto-Novo", language: "French", greeting: "Bonjour", greetingTranslation: "Good day", flagEmoji: "🇧🇯", funFact: "Historic cradle of West African royal kingdoms and remarkable bronze sculpture art.", characterStyle: "african" },
  { name: "Bhutan", continent: "Asia", capital: "Thimphu", language: "Dzongkha", greeting: "Kuzu Zangpo", greetingTranslation: "Hello / Good health", flagEmoji: "🇧🇹", funFact: "Measures national progress using Gross National Happiness rather than standard economic GDP.", characterStyle: "himalayan" },
  { name: "Bolivia", continent: "South America", capital: "Sucre", language: "Spanish / Quechua", greeting: "Kamisaraki", greetingTranslation: "How are you?", flagEmoji: "🇧🇴", funFact: "Contains Salar de Uyuni, an enormous reflective prehistoric salt flat.", characterStyle: "andes" },
  { name: "Bosnia and Herzegovina", continent: "Europe", capital: "Sarajevo", language: "Bosnian / Croatian / Serbian", greeting: "Zdravo", greetingTranslation: "Hello", flagEmoji: "🇧🇦", funFact: "Known for emerald mountain rapids and the historic Ottoman-era bridge in Mostar.", characterStyle: "balkan", aliases: ["bosnia"] },
  { name: "Botswana", continent: "Africa", capital: "Gaborone", language: "Setswana / English", greeting: "Dumela", greetingTranslation: "Greetings", flagEmoji: "🇧🇼", funFact: "The pristine Okavango Delta floods inward into the Kalahari sand basin.", characterStyle: "african" },
  { name: "Brazil", continent: "South America", capital: "Brasília", language: "Portuguese", greeting: "Olá!", greetingTranslation: "Hello!", flagEmoji: "🇧🇷", funFact: "Anchors the Amazon Rainforest, holding roughly 10% of the world's known animal species.", characterStyle: "latino", aliases: ["brasil"] },
  { name: "Brunei", continent: "Asia", capital: "Bandar Seri Begawan", language: "Malay", greeting: "Selamat", greetingTranslation: "Peace", flagEmoji: "🇧🇳", funFact: "Completely surrounds historic stilt water settlements while preserving untouched Borneo rainforests.", characterStyle: "southeast-asia" },
  { name: "Bulgaria", continent: "Europe", capital: "Sofia", language: "Bulgarian", greeting: "Zdrasti", greetingTranslation: "Hello", flagEmoji: "🇧🇬", funFact: "One of the globe's primary producers of fragrant natural rose oils for perfumes.", characterStyle: "slavic" },
  { name: "Burkina Faso", continent: "Africa", capital: "Ouagadougou", language: "French", greeting: "Bonjour", greetingTranslation: "Good morning", flagEmoji: "🇧🇫", funFact: "Its sovereign name translates directly to 'Land of Incorruptible People'.", characterStyle: "african" },
  { name: "Burundi", continent: "Africa", capital: "Gitega", language: "Kirundi / French", greeting: "Amahoro", greetingTranslation: "Peace", flagEmoji: "🇧🇮", funFact: "Legendary for its ancient royal ceremonial drumming troupes and rhythmic traditions.", characterStyle: "african" },

  // C
  { name: "Cabo Verde", continent: "Africa", capital: "Praia", language: "Portuguese", greeting: "Olá", greetingTranslation: "Hello", flagEmoji: "🇨🇻", funFact: "Volcanic Atlantic archipelago famous as the origin of vibrant Morna ballad music.", characterStyle: "island", aliases: ["cape verde"] },
  { name: "Cambodia", continent: "Asia", capital: "Phnom Penh", language: "Khmer", greeting: "Choum Reap Sour", greetingTranslation: "Formal greetings", flagEmoji: "🇰🇭", funFact: "Holds Angkor Wat, the largest historic religious temple monument complex on Earth.", characterStyle: "southeast-asia" },
  { name: "Cameroon", continent: "Africa", capital: "Yaoundé", language: "French / English", greeting: "Bonjour", greetingTranslation: "Hello", flagEmoji: "🇨🇲", funFact: "Known as 'Africa in Miniature' due to its full diversity of ecosystems and climates.", characterStyle: "african" },
  { name: "Canada", continent: "North America", capital: "Ottawa", language: "English / French", greeting: "Hello / Bonjour", greetingTranslation: "Greetings", flagEmoji: "🇨🇦", funFact: "Has the longest total coastline in the world, spanning over 202,000 kilometers.", characterStyle: "nordic" },
  { name: "Central African Republic", continent: "Africa", capital: "Bangui", language: "Sango / French", greeting: "Bala mo", greetingTranslation: "Greetings to you", flagEmoji: "🇨🇫", funFact: "Renowned by astronomers as one of the best locations for viewing the Milky Way without light pollution.", characterStyle: "african", aliases: ["car"] },
  { name: "Chad", continent: "Africa", capital: "N'Djamena", language: "French / Arabic", greeting: "Marhaban", greetingTranslation: "Welcome", flagEmoji: "🇹🇩", funFact: "Features the dramatic sandstone labyrinth spires and desert arches of the Ennedi Plateau.", characterStyle: "sahara" },
  { name: "Chile", continent: "South America", capital: "Santiago", language: "Spanish", greeting: "¡Hola!", greetingTranslation: "Hello!", flagEmoji: "🇨🇱", funFact: "Stretches over 4,300 kilometers north to south, while averaging merely 177 km in width.", characterStyle: "andes" },
  { name: "China", continent: "Asia", capital: "Beijing", language: "Mandarin Chinese", greeting: "Nǐ hǎo", greetingTranslation: "You are well", flagEmoji: "🇨🇳", funFact: "Pioneered the historic inventions of printing, paper currency, gunpowder, and the nautical compass.", characterStyle: "east-asia", aliases: ["prc"] },
  { name: "Colombia", continent: "South America", capital: "Bogotá", language: "Spanish", greeting: "¡Buenas!", greetingTranslation: "Good tidings!", flagEmoji: "🇨🇴", funFact: "The only South American state blessed with coastlines bordering both the Atlantic and Pacific.", characterStyle: "latino" },
  { name: "Comoros", continent: "Africa", capital: "Moroni", language: "Comorian / Arabic", greeting: "Bariza", greetingTranslation: "Peace", flagEmoji: "🇰🇲", funFact: "Commonly known as the 'Perfume Islands' for aromatic ylang-ylang and vanilla crops.", characterStyle: "island" },
  { name: "Costa Rica", continent: "North America", capital: "San José", language: "Spanish", greeting: "¡Pura Vida!", greetingTranslation: "Pure Life!", flagEmoji: "🇨🇷", funFact: "A pioneer in conservation that constitutionally abolished its standing military back in 1948.", characterStyle: "latino" },
  { name: "Croatia", continent: "Europe", capital: "Zagreb", language: "Croatian", greeting: "Bok", greetingTranslation: "Hi", flagEmoji: "🇭🇷", funFact: "Origin land of the necktie fashion accessory, along with over a thousand scenic Adriatic islands.", characterStyle: "balkan" },
  { name: "Cuba", continent: "North America", capital: "Havana", language: "Spanish", greeting: "¡Oye!", greetingTranslation: "Listen / Hey!", flagEmoji: "🇨🇺", funFact: "Famous for classic mid-century vintage automobiles and rich Afro-Cuban jazz traditions.", characterStyle: "caribbean" },
  { name: "Cyprus", continent: "Europe", capital: "Nicosia", language: "Greek / Turkish", greeting: "Geia sas", greetingTranslation: "Health to you", flagEmoji: "🇨🇾", funFact: "Its capital, Nicosia, remains the last divided administrative capital in Europe.", characterStyle: "mediterranean" },
  { name: "Czech Republic", continent: "Europe", capital: "Prague", language: "Czech", greeting: "Ahoj", greetingTranslation: "Ahoy / Hello", flagEmoji: "🇨🇿", funFact: "Boasts the highest density of historic stone castles and châteaux per square mile in Europe.", characterStyle: "european", aliases: ["czechia"] },

  // D
  { name: "Democratic Republic of the Congo", continent: "Africa", capital: "Kinshasa", language: "French / Lingala", greeting: "Mbote", greetingTranslation: "Hello", flagEmoji: "🇨🇩", funFact: "The Congo River flowing through its borders is the deepest river in recorded world geography.", characterStyle: "african", aliases: ["drc", "dr congo", "congo kinshasa"] },
  { name: "Denmark", continent: "Europe", capital: "Copenhagen", language: "Danish", greeting: "Hej", greetingTranslation: "Hi", flagEmoji: "🇩🇰", funFact: "Frequently ranked among the world's happiest nations; inventors of iconic LEGO building blocks.", characterStyle: "nordic" },
  { name: "Djibouti", continent: "Africa", capital: "Djibouti", language: "French / Arabic", greeting: "Salam", greetingTranslation: "Peace", flagEmoji: "🇩🇯", funFact: "Hosts Lake Assal, the lowest geographic land elevation on the entire African continent.", characterStyle: "horn-africa" },
  { name: "Dominica", continent: "North America", capital: "Roseau", language: "English", greeting: "Hello", greetingTranslation: "Hello", flagEmoji: "🇩🇲", funFact: "Known as 'The Nature Island' because of its bubbling thermal boiling lake and rainforests.", characterStyle: "caribbean" },
  { name: "Dominican Republic", continent: "North America", capital: "Santo Domingo", language: "Spanish", greeting: "¡Saludos!", greetingTranslation: "Greetings!", flagEmoji: "🇩🇴", funFact: "Santo Domingo holds the oldest continuously inhabited European-built cathedral in the Americas.", characterStyle: "caribbean", aliases: ["dr"] },

  // E
  { name: "Ecuador", continent: "South America", capital: "Quito", language: "Spanish", greeting: "¡Hola!", greetingTranslation: "Hello!", flagEmoji: "🇪🇨", funFact: "Named after the Equator; the summit of Mount Chimborazo is the closest point on Earth to space.", characterStyle: "andes" },
  { name: "Egypt", continent: "Africa", capital: "Cairo", language: "Arabic", greeting: "Ahlan", greetingTranslation: "Welcome", flagEmoji: "🇪🇬", funFact: "Home to the Pyramids of Giza, the sole surviving wonders of the original ancient world.", characterStyle: "north-africa" },
  { name: "El Salvador", continent: "North America", capital: "San Salvador", language: "Spanish", greeting: "¿Qué tal?", greetingTranslation: "How is it going?", flagEmoji: "🇸🇻", funFact: "Known as the 'Land of Volcanoes' because of regular seismic and geothermal volcanic peaks.", characterStyle: "latino" },
  { name: "Equatorial Guinea", continent: "Africa", capital: "Malabo", language: "Spanish / French", greeting: "Hola", greetingTranslation: "Hello", flagEmoji: "🇬🇶", funFact: "The only sovereign country in mainland Africa where Spanish is an official constitutional language.", characterStyle: "african" },
  { name: "Eritrea", continent: "Africa", capital: "Asmara", language: "Tigrinya / Arabic", greeting: "Selam", greetingTranslation: "Peace", flagEmoji: "🇪🇷", funFact: "Its capital, Asmara, is a UNESCO World Heritage site filled with preserved Italian modernist art-deco architecture.", characterStyle: "horn-africa" },
  { name: "Estonia", continent: "Europe", capital: "Tallinn", language: "Estonian", greeting: "Tere", greetingTranslation: "Hello", flagEmoji: "🇪🇪", funFact: "A global digital powerhouse where virtually all public civic interactions occur online.", characterStyle: "nordic" },
  { name: "Eswatini", continent: "Africa", capital: "Mbabane", language: "Swazi / English", greeting: "Sawubona", greetingTranslation: "I see you", flagEmoji: "🇸🇿", funFact: "One of the world's few surviving absolute monarchies, famed for traditional cultural festivals.", characterStyle: "african", aliases: ["swaziland"] },
  { name: "Ethiopia", continent: "Africa", capital: "Addis Ababa", language: "Amharic", greeting: "Tena Yistilign", greetingTranslation: "May God give you health", flagEmoji: "🇪🇹", funFact: "The historic birthplace of coffee arabica, utilizing its own unique 13-month calendar.", characterStyle: "horn-africa" },

  // F
  { name: "Fiji", continent: "Oceania", capital: "Suva", language: "English / Fijian", greeting: "Bula!", greetingTranslation: "Life and good health!", flagEmoji: "🇫🇯", funFact: "Spans across the 180-degree International Date Line across its peaceful volcanic isles.", characterStyle: "oceanian" },
  { name: "Finland", continent: "Europe", capital: "Helsinki", language: "Finnish / Swedish", greeting: "Moi", greetingTranslation: "Hi", flagEmoji: "🇫🇮", funFact: "Contains roughly 3 million thermal saunas for a national population of 5.5 million people.", characterStyle: "nordic" },
  { name: "France", continent: "Europe", capital: "Paris", language: "French", greeting: "Bonjour", greetingTranslation: "Good day", flagEmoji: "🇫🇷", funFact: "Produces hundreds of strictly regulated AOC artisanal cheeses and fine culinary staples.", characterStyle: "european" },

  // G
  { name: "Gabon", continent: "Africa", capital: "Libreville", language: "French", greeting: "Bonjour", greetingTranslation: "Good day", flagEmoji: "🇬🇦", funFact: "Over 85% of its entire territory is cloaked in dense, biodiverse equatorial rainforests.", characterStyle: "african" },
  { name: "Gambia", continent: "Africa", capital: "Banjul", language: "English", greeting: "Hello", greetingTranslation: "Hello", flagEmoji: "🇬🇲", funFact: "The smallest nation in mainland Africa, following the winding curves of the Gambia River.", characterStyle: "african", aliases: ["the gambia"] },
  { name: "Georgia", continent: "Asia", capital: "Tbilisi", language: "Georgian", greeting: "Gamarjoba", greetingTranslation: "Victory to you", flagEmoji: "🇬🇪", funFact: "Regarded as the cradle of wine; vintners have buried clay kvevri jars here for 8,000 years.", characterStyle: "caucasus" },
  { name: "Germany", continent: "Europe", capital: "Berlin", language: "German", greeting: "Guten Tag", greetingTranslation: "Good day", flagEmoji: "🇩🇪", funFact: "Renowned for pioneering advanced engineering, classical philosophy, and the Autobahn highway.", characterStyle: "european", aliases: ["deutschland"] },
  { name: "Ghana", continent: "Africa", capital: "Accra", language: "English", greeting: "Akwaaba", greetingTranslation: "Welcome", flagEmoji: "🇬🇭", funFact: "The first nation in Sub-Saharan Africa to achieve independence from colonial authority.", characterStyle: "african" },
  { name: "Greece", continent: "Europe", capital: "Athens", language: "Greek", greeting: "Geia sou", greetingTranslation: "Health to you", flagEmoji: "🇬🇷", funFact: "Cradle of Western democracy, formal geometry, dramatic theater, and the Olympic Games.", characterStyle: "mediterranean", aliases: ["hellas"] },
  { name: "Grenada", continent: "North America", capital: "St. George's", language: "English", greeting: "Greetings", greetingTranslation: "Greetings", flagEmoji: "🇬🇩", funFact: "Celebrated as the 'Spice Isle' for its vast exports of natural nutmeg and mace spices.", characterStyle: "caribbean" },
  { name: "Guatemala", continent: "North America", capital: "Guatemala City", language: "Spanish", greeting: "Hola", greetingTranslation: "Hello", flagEmoji: "🇬🇹", funFact: "The heart of ancient Maya civilization, home to towering jungle pyramids at Tikal.", characterStyle: "latino" },
  { name: "Guinea", continent: "Africa", capital: "Conakry", language: "French", greeting: "I ni sogoma", greetingTranslation: "Good morning", flagEmoji: "🇬🇳", funFact: "Serves as the water tower of West Africa, originating both the Niger and Senegal rivers.", characterStyle: "african" },
  { name: "Guinea-Bissau", continent: "Africa", capital: "Bissau", language: "Portuguese", greeting: "Ola", greetingTranslation: "Hello", flagEmoji: "🇬🇼", funFact: "Encompasses the Bijagós Archipelago, where saltwater hippos swim in ocean estuaries.", characterStyle: "african" },
  { name: "Guyana", continent: "South America", capital: "Georgetown", language: "English", greeting: "Ayup", greetingTranslation: "Hello", flagEmoji: "🇬🇾", funFact: "Kaieteur Falls drops 226 meters, making it the world's largest single-drop waterfall by volume.", characterStyle: "caribbean" },

  // H
  { name: "Haiti", continent: "North America", capital: "Port-au-Prince", language: "French / Haitian Creole", greeting: "Sak pase", greetingTranslation: "What's happening", flagEmoji: "🇭🇹", funFact: "The world's first republic established by self-liberated formerly enslaved people.", characterStyle: "caribbean" },
  { name: "Honduras", continent: "North America", capital: "Tegucigalpa", language: "Spanish", greeting: "¡Buenas!", greetingTranslation: "Good day!", flagEmoji: "🇭🇳", funFact: "Contains Copán, celebrated for the most intricately carved hieroglyphic stairways of the Maya.", characterStyle: "latino" },
  { name: "Hungary", continent: "Europe", capital: "Budapest", language: "Hungarian", greeting: "Sziasztok", greetingTranslation: "Hi everyone", flagEmoji: "🇭🇺", funFact: "Budapest rests upon hundreds of natural geothermal mineral springs and bath complexes.", characterStyle: "european" },

  // I
  { name: "Iceland", continent: "Europe", capital: "Reykjavik", language: "Icelandic", greeting: "Góðan dag", greetingTranslation: "Good day", flagEmoji: "🇮🇸", funFact: "Runs almost entirely on renewable geothermal and hydro energy, with zero native mosquitoes.", characterStyle: "nordic" },
  { name: "India", continent: "Asia", capital: "New Delhi", language: "Hindi / English", greeting: "Namaste", greetingTranslation: "I bow to the divine in you", flagEmoji: "🇮🇳", funFact: "The world's most populous nation, pioneer of zero in mathematics and ancient yoga.", characterStyle: "south-asia", aliases: ["bharat"] },
  { name: "Indonesia", continent: "Asia", capital: "Jakarta", language: "Indonesian", greeting: "Halo", greetingTranslation: "Hello", flagEmoji: "🇮🇩", funFact: "The planet's largest island state, counting over 17,500 distinct tropical isles.", characterStyle: "southeast-asia" },
  { name: "Iran", continent: "Asia", capital: "Tehran", language: "Persian (Farsi)", greeting: "Dorood", greetingTranslation: "Greetings", flagEmoji: "🇮🇷", funFact: "Home to ancient Persepolis and masterworks of hand-knotted silk and wool Persian rugs.", characterStyle: "middle-east", aliases: ["persia"] },
  { name: "Iraq", continent: "Asia", capital: "Baghdad", language: "Arabic / Kurdish", greeting: "Marhaba", greetingTranslation: "Welcome", flagEmoji: "🇮🇶", funFact: "Historic Mesopotamia, widely recognized by historians as the fertile cradle of human civilization.", characterStyle: "middle-east" },
  { name: "Ireland", continent: "Europe", capital: "Dublin", language: "Irish / English", greeting: "Dia dhuit", greetingTranslation: "God be with you", flagEmoji: "🇮🇪", funFact: "Known as the Emerald Isle; it has historically produced four Nobel laureates in literature.", characterStyle: "celtic" },
  { name: "Israel", continent: "Asia", capital: "Jerusalem", language: "Hebrew / Arabic", greeting: "Shalom", greetingTranslation: "Peace", flagEmoji: "🇮🇱", funFact: "Pioneered drip irrigation technology and contains the Dead Sea, Earth's lowest water body.", characterStyle: "middle-east" },
  { name: "Italy", continent: "Europe", capital: "Rome", language: "Italian", greeting: "Ciao!", greetingTranslation: "Hi / Goodbye!", flagEmoji: "🇮🇹", funFact: "Holds more recognized UNESCO World Heritage cultural sites than any other country on the globe.", characterStyle: "mediterranean", aliases: ["italia"] },

  // J
  { name: "Jamaica", continent: "North America", capital: "Kingston", language: "English", greeting: "Wah gwaan", greetingTranslation: "What is going on", flagEmoji: "🇯🇲", funFact: "Birthplace of reggae music, blue mountain coffee beans, and world-record sprinters.", characterStyle: "caribbean" },
  { name: "Japan", continent: "Asia", capital: "Tokyo", language: "Japanese", greeting: "Konnichiwa", greetingTranslation: "Good afternoon", flagEmoji: "🇯🇵", funFact: "Features high-speed Shinkansen bullet trains that have operated for decades with zero passenger fatalities.", characterStyle: "east-asia", aliases: ["nippon", "nihon"] },
  { name: "Jordan", continent: "Asia", capital: "Amman", language: "Arabic", greeting: "Marhaba", greetingTranslation: "Welcome", flagEmoji: "🇯🇴", funFact: "Contains the ancient rose-red rock city of Petra, hand-carved into sheer sandstone cliffs.", characterStyle: "middle-east" },

  // K
  { name: "Kazakhstan", continent: "Asia", capital: "Astana", language: "Kazakh / Russian", greeting: "Salem", greetingTranslation: "Hello", flagEmoji: "🇰🇿", funFact: "The largest landlocked nation on Earth; wild domestic apples originally originated in its mountains.", characterStyle: "central-asia" },
  { name: "Kenya", continent: "Africa", capital: "Nairobi", language: "Swahili / English", greeting: "Jambo", greetingTranslation: "Hello", flagEmoji: "🇰🇪", funFact: "Hosts the annual Great Migration, where millions of wildebeest cross the Mara River.", characterStyle: "african" },
  { name: "Kiribati", continent: "Oceania", capital: "South Tarawa", language: "Gilbertese / English", greeting: "Mauri", greetingTranslation: "Blessings", flagEmoji: "🇰🇮", funFact: "The only nation on Earth situated across all four cardinal planetary hemispheres.", characterStyle: "oceanian" },
  { name: "Kuwait", continent: "Asia", capital: "Kuwait City", language: "Arabic", greeting: "Hala", greetingTranslation: "Welcome", flagEmoji: "🇰🇼", funFact: "The Kuwaiti Dinar consistently ranks as the world's highest-valued sovereign currency unit.", characterStyle: "middle-east" },
  { name: "Kyrgyzstan", continent: "Asia", capital: "Bishkek", language: "Kyrgyz / Russian", greeting: "Salamatsyzby", greetingTranslation: "Are you well?", flagEmoji: "🇰🇬", funFact: "Dominated by the celestial Tian Shan peaks, with over 90% of its land elevated over 1,000m.", characterStyle: "central-asia" },

  // L
  { name: "Laos", continent: "Asia", capital: "Vientiane", language: "Lao", greeting: "Sabaidee", greetingTranslation: "Good health", flagEmoji: "🇱🇦", funFact: "The only landlocked country in Southeast Asia, traversed by the sweeping Mekong River.", characterStyle: "southeast-asia" },
  { name: "Latvia", continent: "Europe", capital: "Riga", language: "Latvian", greeting: "Sveiki", greetingTranslation: "Greetings", flagEmoji: "🇱🇻", funFact: "Riga showcases one of the world's finest collections of historic Art Nouveau architecture.", characterStyle: "nordic" },
  { name: "Lebanon", continent: "Asia", capital: "Beirut", language: "Arabic / French", greeting: "Marhaba", greetingTranslation: "Hello", flagEmoji: "🇱🇧", funFact: "Its national symbol, the mighty Cedar of Lebanon, is mentioned dozens of times in ancient epic poetry.", characterStyle: "middle-east" },
  { name: "Lesotho", continent: "Africa", capital: "Maseru", language: "Sesotho / English", greeting: "Khotso", greetingTranslation: "Peace", flagEmoji: "🇱🇸", funFact: "Enclosed entirely inside South Africa, it is the only state completely lying above 1,400 meters elevation.", characterStyle: "african" },
  { name: "Liberia", continent: "Africa", capital: "Monrovia", language: "English", greeting: "Hello", greetingTranslation: "Hello", flagEmoji: "🇱🇷", funFact: "Africa's oldest modern republic, named after liberty upon its 1847 independence.", characterStyle: "african" },
  { name: "Libya", continent: "Africa", capital: "Tripoli", language: "Arabic", greeting: "Salam", greetingTranslation: "Peace", flagEmoji: "🇱🇾", funFact: "Over 90% of its terrain consists of the immense, wind-carved Sahara desert dunes.", characterStyle: "north-africa" },
  { name: "Liechtenstein", continent: "Europe", capital: "Vaduz", language: "German", greeting: "Grüezi", greetingTranslation: "Greetings", flagEmoji: "🇱🇮", funFact: "One of only two doubly landlocked countries globally (surrounded only by landlocked neighbors).", characterStyle: "alpine" },
  { name: "Lithuania", continent: "Europe", capital: "Vilnius", language: "Lithuanian", greeting: "Labas", greetingTranslation: "Hello", flagEmoji: "🇱🇹", funFact: "Its native language is one of the oldest living Indo-European tongues, closely related to Sanskrit.", characterStyle: "nordic" },
  { name: "Luxembourg", continent: "Europe", capital: "Luxembourg City", language: "Luxembourgish / French / German", greeting: "Moien", greetingTranslation: "Good morning", flagEmoji: "🇱🇺", funFact: "The first nation worldwide to institute completely free nationwide public transit for everyone.", characterStyle: "european" },

  // M
  { name: "Madagascar", continent: "Africa", capital: "Antananarivo", language: "Malagasy / French", greeting: "Salama", greetingTranslation: "Peace/Hello", flagEmoji: "🇲🇬", funFact: "Roughly 90% of all wildlife found here, including wild lemurs, exists nowhere else on Earth.", characterStyle: "island" },
  { name: "Malawi", continent: "Africa", capital: "Lilongwe", language: "Chichewa / English", greeting: "Moni", greetingTranslation: "Greetings", flagEmoji: "🇲🇼", funFact: "Affectionately called the 'Warm Heart of Africa' for the welcoming hospitality of its populace.", characterStyle: "african" },
  { name: "Malaysia", continent: "Asia", capital: "Kuala Lumpur", language: "Malay", greeting: "Selamat pagi", greetingTranslation: "Good morning", flagEmoji: "🇲🇾", funFact: "Home to the iconic Petronas Towers, which held the title of world's tallest buildings for years.", characterStyle: "southeast-asia" },
  { name: "Maldives", continent: "Asia", capital: "Malé", language: "Dhivehi", greeting: "Assalaamu Alaikum", greetingTranslation: "Peace be upon you", flagEmoji: "🇲🇻", funFact: "The lowest terrain country on Earth, with an average natural ground elevation of just 1.5 meters.", characterStyle: "island" },
  { name: "Mali", continent: "Africa", capital: "Bamako", language: "Bambara / French", greeting: "I ni ce", greetingTranslation: "Hello / Thanks", flagEmoji: "🇲🇱", funFact: "Hosts the Great Mosque of Djenné, the largest preserved adobe mud-brick building in the world.", characterStyle: "sahara" },
  { name: "Malta", continent: "Europe", capital: "Valletta", language: "Maltese / English", greeting: "Bongu", greetingTranslation: "Good morning", flagEmoji: "🇲🇹", funFact: "Its megalithic stone temples are older than Stonehenge and the Pyramids of Egypt.", characterStyle: "mediterranean" },
  { name: "Marshall Islands", continent: "Oceania", capital: "Majuro", language: "Marshallese / English", greeting: "Iakwe", greetingTranslation: "Love and warmth", flagEmoji: "🇲🇭", funFact: "Traditional navigators sailed open seas using complex wave-swelling stick charts.", characterStyle: "oceanian" },
  { name: "Mauritania", continent: "Africa", capital: "Nouakchott", language: "Arabic", greeting: "Salam", greetingTranslation: "Peace", flagEmoji: "🇲🇷", funFact: "Contains the 'Eye of the Sahara' (Richat Structure), an enigmatic circular geological dome.", characterStyle: "sahara" },
  { name: "Mauritius", continent: "Africa", capital: "Port Louis", language: "English / Creole", greeting: "Bonzour", greetingTranslation: "Good day", flagEmoji: "🇲🇺", funFact: "Was the sole natural home of the flightless dodo bird prior to its extinction in the 17th century.", characterStyle: "island" },
  { name: "Mexico", continent: "North America", capital: "Mexico City", language: "Spanish", greeting: "¡Hola!", greetingTranslation: "Hello!", flagEmoji: "🇲🇽", funFact: "Gifted the modern world chocolate, vanilla, and the ancient culinary tradition of corn tortillas.", characterStyle: "latino" },
  { name: "Micronesia", continent: "Oceania", capital: "Palikir", language: "English", greeting: "Ran annim", greetingTranslation: "Good day", flagEmoji: "🇫🇲", funFact: "Contains Nan Madol, a mysterious ancient stone city built atop coral reef canals.", characterStyle: "oceanian", aliases: ["fsm"] },
  { name: "Moldova", continent: "Europe", capital: "Chisinau", language: "Romanian", greeting: "Salut", greetingTranslation: "Greetings", flagEmoji: "🇲🇩", funFact: "Mileștii Mici holds the Guinness record for the world's largest underground wine cellar labyrinth.", characterStyle: "european" },
  { name: "Monaco", continent: "Europe", capital: "Monaco", language: "French", greeting: "Bonjour", greetingTranslation: "Hello", flagEmoji: "🇲🇨", funFact: "The second smallest independent microstate in the world after Vatican City, famous for its Grand Prix.", characterStyle: "mediterranean" },
  { name: "Mongolia", continent: "Asia", capital: "Ulaanbaatar", language: "Mongolian", greeting: "Sain baina uu", greetingTranslation: "Are you well?", flagEmoji: "🇲🇳", funFact: "The least densely populated sovereign nation on Earth, preserving nomadic equestrian culture.", characterStyle: "steppes" },
  { name: "Montenegro", continent: "Europe", capital: "Podgorica", language: "Montenegrin", greeting: "Zdravo", greetingTranslation: "Hello", flagEmoji: "🇲🇪", funFact: "Features the dramatic Bay of Kotor, often termed Europe's southernmost coastal fjord.", characterStyle: "balkan" },
  { name: "Morocco", continent: "Africa", capital: "Rabat", language: "Arabic / Berber", greeting: "Salam", greetingTranslation: "Peace", flagEmoji: "🇲🇦", funFact: "Home to the University of al-Qarawiyyin in Fez, the oldest continuously operating university.", characterStyle: "north-africa" },
  { name: "Mozambique", continent: "Africa", capital: "Maputo", language: "Portuguese", greeting: "Bom dia", greetingTranslation: "Good day", flagEmoji: "🇲🇿", funFact: "Its coastal waters shelter rare dugongs, swimming along untouched coral atolls.", characterStyle: "african" },
  { name: "Myanmar", continent: "Asia", capital: "Naypyidaw", language: "Burmese", greeting: "Mingalaba", greetingTranslation: "Auspicious blessings", flagEmoji: "🇲🇲", funFact: "The ancient plain of Bagan contains more than 2,000 preserved Buddhist pagodas and temples.", characterStyle: "southeast-asia", aliases: ["burma"] },

  // N
  { name: "Namibia", continent: "Africa", capital: "Windhoek", language: "English", greeting: "Hello", greetingTranslation: "Hello", flagEmoji: "🇳🇦", funFact: "The Namib Desert is widely recognized by geologists as the oldest desert on Earth.", characterStyle: "african" },
  { name: "Nauru", continent: "Oceania", capital: "Yaren (de facto)", language: "Nauruan / English", greeting: "Ekabow", greetingTranslation: "Hello", flagEmoji: "🇳🇷", funFact: "The smallest island nation worldwide, covering just 21 square kilometers total area.", characterStyle: "oceanian" },
  { name: "Nepal", continent: "Asia", capital: "Kathmandu", language: "Nepali", greeting: "Namaste", greetingTranslation: "I greet the divine in you", flagEmoji: "🇳🇵", funFact: "The world's only sovereign state with a non-quadrilateral flag; home to Mount Everest.", characterStyle: "himalayan" },
  { name: "Netherlands", continent: "Europe", capital: "Amsterdam", language: "Dutch", greeting: "Hallo", greetingTranslation: "Hello", flagEmoji: "🇳🇱", funFact: "Over a quarter of its geographic landmass lies directly below sea level, protected by dykes.", characterStyle: "european", aliases: ["holland"] },
  { name: "New Zealand", continent: "Oceania", capital: "Wellington", language: "English / Māori", greeting: "Kia Ora", greetingTranslation: "Be well", flagEmoji: "🇳🇿", funFact: "The first self-governing nation on Earth where women achieved the constitutional right to vote.", characterStyle: "oceanian", aliases: ["aotearoa"] },
  { name: "Nicaragua", continent: "North America", capital: "Managua", language: "Spanish", greeting: "¡Hola!", greetingTranslation: "Hello!", flagEmoji: "🇳🇮", funFact: "Lake Nicaragua is home to rare oceanic freshwater bull sharks that adapted to inland water.", characterStyle: "latino" },
  { name: "Niger", continent: "Africa", capital: "Niamey", language: "French", greeting: "Salam", greetingTranslation: "Peace", flagEmoji: "🇳🇪", funFact: "Pioneered early prehistoric bronze casting in the Air Mountains region thousands of years ago.", characterStyle: "sahara" },
  { name: "Nigeria", continent: "Africa", capital: "Abuja", language: "English", greeting: "Bawo ni", greetingTranslation: "How are things", flagEmoji: "🇳🇬", funFact: "Africa's most populous nation; its 'Nollywood' cinema produces thousands of films annually.", characterStyle: "african" },
  { name: "North Korea", continent: "Asia", capital: "Pyongyang", language: "Korean", greeting: "Annyeonghaseyo", greetingTranslation: "Peace", flagEmoji: "🇰🇵", funFact: "Uses the Juche calendar, counting years from the birth of founding figure Kim Il Sung.", characterStyle: "east-asia", aliases: ["dprk"] },
  { name: "North Macedonia", continent: "Europe", capital: "Skopje", language: "Macedonian", greeting: "Zdravo", greetingTranslation: "Hello", flagEmoji: "🇲🇰", funFact: "Lake Ohrid is one of Europe's deepest and oldest natural lake ecosystems.", characterStyle: "balkan", aliases: ["macedonia"] },
  { name: "Norway", continent: "Europe", capital: "Oslo", language: "Norwegian", greeting: "Hei", greetingTranslation: "Hi", flagEmoji: "🇳🇴", funFact: "Famed for scenic fjords, the midnight sun, and granting the Nobel Peace Prize annually.", characterStyle: "nordic" },

  // O
  { name: "Oman", continent: "Asia", capital: "Muscat", language: "Arabic", greeting: "Marhaba", greetingTranslation: "Welcome", flagEmoji: "🇴🇲", funFact: "One of the oldest continuously independent Arab states, historic navigators of the Indian Ocean.", characterStyle: "middle-east" },

  // P
  { name: "Pakistan", continent: "Asia", capital: "Islamabad", language: "Urdu / English", greeting: "Assalam-o-Alaikum", greetingTranslation: "Peace be upon you", flagEmoji: "🇵🇰", funFact: "Produces over half of the world's hand-stitched professional FIFA soccer match balls in Sialkot.", characterStyle: "south-asia" },
  { name: "Palau", continent: "Oceania", capital: "Ngerulmud", language: "Palauan / English", greeting: "Alii", greetingTranslation: "Hello", flagEmoji: "🇵🇼", funFact: "Created the world's first national conservation pledge stamped directly into visiting passports.", characterStyle: "oceanian" },
  { name: "Panama", continent: "North America", capital: "Panama City", language: "Spanish", greeting: "¿Qué xopá?", greetingTranslation: "What's up?", flagEmoji: "🇵🇦", funFact: "The Panama Canal cuts through the continental divide, connecting the Pacific and Atlantic oceans.", characterStyle: "latino" },
  { name: "Papua New Guinea", continent: "Oceania", capital: "Port Moresby", language: "Tok Pisin / English", greeting: "Halo", greetingTranslation: "Hello", flagEmoji: "🇵🇬", funFact: "The most linguistically diverse nation in existence, boasting over 840 living languages.", characterStyle: "oceanian", aliases: ["png"] },
  { name: "Paraguay", continent: "South America", capital: "Asunción", language: "Spanish / Guaraní", greeting: "Mba'éichapa", greetingTranslation: "How are you?", flagEmoji: "🇵🇾", funFact: "A majority of its population fluently speaks Guaraní, an indigenous American language.", characterStyle: "latino" },
  { name: "Peru", continent: "South America", capital: "Lima", language: "Spanish / Quechua", greeting: "Allillanchu", greetingTranslation: "Are you well?", flagEmoji: "🇵🇪", funFact: "Homeland of the Inca Empire and the mysterious high-altitude citadel of Machu Picchu.", characterStyle: "andes" },
  { name: "Philippines", continent: "Asia", capital: "Manila", language: "Filipino / English", greeting: "Kamusta", greetingTranslation: "How are you", flagEmoji: "🇵🇭", funFact: "Comprises over 7,640 tropical islands and hosts the world's longest festive Christmas season.", characterStyle: "southeast-asia" },
  { name: "Poland", continent: "Europe", capital: "Warsaw", language: "Polish", greeting: "Cześć", greetingTranslation: "Hi", flagEmoji: "🇵🇱", funFact: "Encompasses the Wieliczka Salt Mine, which features entire subterranean chapels carved from rock salt.", characterStyle: "slavic" },
  { name: "Portugal", continent: "Europe", capital: "Lisbon", language: "Portuguese", greeting: "Olá", greetingTranslation: "Hello", flagEmoji: "🇵🇹", funFact: "Produces roughly half of the entire world's harvest of natural tree cork stoppers.", characterStyle: "mediterranean" },

  // Q
  { name: "Qatar", continent: "Asia", capital: "Doha", language: "Arabic", greeting: "Marhaba", greetingTranslation: "Welcome", flagEmoji: "🇶🇦", funFact: "Has no natural permanent freshwater rivers or lakes, relying completely on state-of-the-art desalination.", characterStyle: "middle-east" },

  // R
  { name: "Romania", continent: "Europe", capital: "Bucharest", language: "Romanian", greeting: "Bună", greetingTranslation: "Good day", flagEmoji: "🇷🇴", funFact: "The Carpathian Mountains are home to Europe's largest population of wild brown bears.", characterStyle: "balkan" },
  { name: "Russia", continent: "Europe", capital: "Moscow", language: "Russian", greeting: "Privet", greetingTranslation: "Hi", flagEmoji: "🇷🇺", funFact: "The largest nation on Earth by area, spanning 11 distinct geographical time zones.", characterStyle: "slavic", aliases: ["russian federation"] },
  { name: "Rwanda", continent: "Africa", capital: "Kigali", language: "Kinyarwanda / French", greeting: "Muraho", greetingTranslation: "Hello", flagEmoji: "🇷🇼", funFact: "Celebrated as the 'Land of a Thousand Hills' and a pioneer in banishing single-use plastic bags.", characterStyle: "african" },

  // S
  { name: "Saint Kitts and Nevis", continent: "North America", capital: "Basseterre", language: "English", greeting: "Hello", greetingTranslation: "Hello", flagEmoji: "🇰🇳", funFact: "The smallest independent sovereign country in the entire Western Hemisphere.", characterStyle: "caribbean", aliases: ["st kitts"] },
  { name: "Saint Lucia", continent: "North America", capital: "Castries", language: "English", greeting: "Sa ka fèt", greetingTranslation: "How are things", flagEmoji: "🇱🇨", funFact: "The only nation named after an actual historical woman (Saint Lucy of Syracuse).", characterStyle: "caribbean", aliases: ["st lucia"] },
  { name: "Saint Vincent and the Grenadines", continent: "North America", capital: "Kingstown", language: "English", greeting: "Good day", greetingTranslation: "Good day", flagEmoji: "🇻🇨", funFact: "Features pristine volcanic sand beaches and lush rainforest wildlife preserves.", characterStyle: "caribbean", aliases: ["st vincent"] },
  { name: "Samoa", continent: "Oceania", capital: "Apia", language: "Samoan / English", greeting: "Talofa", greetingTranslation: "Greetings", flagEmoji: "🇼🇸", funFact: "Maintains 'Fa'a Samoa', an ancient, 3,000-year-old traditional communal social code.", characterStyle: "oceanian" },
  { name: "San Marino", continent: "Europe", capital: "San Marino", language: "Italian", greeting: "Salve", greetingTranslation: "Greetings", flagEmoji: "🇸🇲", funFact: "Claims to be the world's oldest surviving sovereign republic, founded in 301 CE.", characterStyle: "mediterranean" },
  { name: "Sao Tome and Principe", continent: "Africa", capital: "São Tomé", language: "Portuguese", greeting: "Olá", greetingTranslation: "Hello", flagEmoji: "🇸🇹", funFact: "Once called the 'Chocolate Islands' when it was the world's top producer of cocoa beans.", characterStyle: "island" },
  { name: "Saudi Arabia", continent: "Asia", capital: "Riyadh", language: "Arabic", greeting: "Salam Alaykum", greetingTranslation: "Peace be upon you", flagEmoji: "🇸🇦", funFact: "Contains the Rub' al Khali (Empty Quarter), the vastest continuous sand desert expanse on Earth.", characterStyle: "middle-east", aliases: ["ksa"] },
  { name: "Senegal", continent: "Africa", capital: "Dakar", language: "Wolof / French", greeting: "Nanga def", greetingTranslation: "How are you", flagEmoji: "🇸🇳", funFact: "Lake Retba near Dakar shines bright bubblegum pink due to harmless salt-loving micro-algae.", characterStyle: "african" },
  { name: "Serbia", continent: "Europe", capital: "Belgrade", language: "Serbian", greeting: "Zdravo", greetingTranslation: "Hello", flagEmoji: "🇷🇸", funFact: "Belgrade sits at the confluence of the Sava and Danube, inhabited since prehistoric times.", characterStyle: "balkan" },
  { name: "Seychelles", continent: "Africa", capital: "Victoria", language: "Seychellois Creole / French", greeting: "Bonzour", greetingTranslation: "Good day", flagEmoji: "🇸🇨", funFact: "Home to the rare Coco de Mer palm, which yields the largest, heaviest wild seed in botany.", characterStyle: "island" },
  { name: "Sierra Leone", continent: "Africa", capital: "Freetown", language: "English / Krio", greeting: "Kusheh", greetingTranslation: "Greetings", flagEmoji: "🇸🇱", funFact: "Freetown was founded in 1792 as an intentional haven for repatriated freed slaves.", characterStyle: "african" },
  { name: "Singapore", continent: "Asia", capital: "Singapore", language: "English / Malay / Mandarin", greeting: "Hello / Nǐ hǎo", greetingTranslation: "Greetings", flagEmoji: "🇸🇬", funFact: "A modern city-state renowned for its biophilic supertree vertical gardens and sustainability.", characterStyle: "southeast-asia" },
  { name: "Slovakia", continent: "Europe", capital: "Bratislava", language: "Slovak", greeting: "Dobrý deň", greetingTranslation: "Good day", flagEmoji: "🇸🇰", funFact: "Bratislava is the only national capital bordering two distinct foreign sovereign countries (Austria and Hungary).", characterStyle: "slavic" },
  { name: "Slovenia", continent: "Europe", capital: "Ljubljana", language: "Slovene", greeting: "Živjo", greetingTranslation: "Hi", flagEmoji: "🇸🇮", funFact: "Features picturesque Lake Bled with its iconic island church and castle perched above glacial waters.", characterStyle: "alpine" },
  { name: "Solomon Islands", continent: "Oceania", capital: "Honiara", language: "English / Pijin", greeting: "Halo", greetingTranslation: "Hello", flagEmoji: "🇸🇧", funFact: "Its waters hold WWII shipwrecks that have transformed into flourishing coral reefs.", characterStyle: "oceanian" },
  { name: "Somalia", continent: "Africa", capital: "Mogadishu", language: "Somali / Arabic", greeting: "Iska warran", greetingTranslation: "What's the news", flagEmoji: "🇸🇴", funFact: "Boasts the longest coastal shoreline on the mainland continent of Africa.", characterStyle: "horn-africa" },
  { name: "South Africa", continent: "Africa", capital: "Pretoria / Cape Town / Bloemfontein", language: "12 Official Languages", greeting: "Sawubona", greetingTranslation: "I see you", flagEmoji: "🇿🇦", funFact: "Known as the 'Rainbow Nation'; uniquely features three separate official governmental capitals.", characterStyle: "african", aliases: ["rsa"] },
  { name: "South Korea", continent: "Asia", capital: "Seoul", language: "Korean", greeting: "Annyeonghaseyo", greetingTranslation: "Peace and wellness", flagEmoji: "🇰🇷", funFact: "Global epicenter of K-pop, high-speed fiber internet infrastructure, and advanced consumer electronics.", characterStyle: "east-asia", aliases: ["korea", "republic of korea"] },
  { name: "South Sudan", continent: "Africa", capital: "Juba", language: "English", greeting: "Kudu", greetingTranslation: "Welcome", flagEmoji: "🇸🇸", funFact: "The youngest internationally recognized sovereign state, achieving independence in 2011.", characterStyle: "african" },
  { name: "Spain", continent: "Europe", capital: "Madrid", language: "Spanish", greeting: "¡Hola!", greetingTranslation: "Hello!", flagEmoji: "🇪🇸", funFact: "Produces roughly half of the entire planet's culinary virgin olive oil harvest.", characterStyle: "mediterranean", aliases: ["espana"] },
  { name: "Sri Lanka", continent: "Asia", capital: "Sri Jayawardenepura Kotte", language: "Sinhala / Tamil", greeting: "Ayubowan", greetingTranslation: "May you live long", flagEmoji: "🇱🇰", funFact: "Known as the 'Pearl of the Indian Ocean', famed for exquisite Ceylon tea cultivation.", characterStyle: "south-asia", aliases: ["ceylon"] },
  { name: "Sudan", continent: "Africa", capital: "Khartoum", language: "Arabic / English", greeting: "Salam", greetingTranslation: "Peace", flagEmoji: "🇸🇩", funFact: "Houses over 200 ancient Nubian pyramids—exceeding the total count discovered in Egypt.", characterStyle: "sahara" },
  { name: "Suriname", continent: "South America", capital: "Paramaribo", language: "Dutch", greeting: "Fa waka", greetingTranslation: "How are you", flagEmoji: "🇸🇷", funFact: "The smallest sovereign country in South America, covered mostly by pristine rainforest.", characterStyle: "latino" },
  { name: "Sweden", continent: "Europe", capital: "Stockholm", language: "Swedish", greeting: "Hej", greetingTranslation: "Hi", flagEmoji: "🇸🇪", funFact: "Invented the three-point automobile seatbelt and deliberately gave away the patent to save lives.", characterStyle: "nordic" },
  { name: "Switzerland", continent: "Europe", capital: "Bern", language: "German / French / Italian / Romansh", greeting: "Grüezi", greetingTranslation: "Greetings", flagEmoji: "🇨🇭", funFact: "Home to the Alps, precision horology watches, and delicious artisan alpine milk chocolate.", characterStyle: "alpine" },
  { name: "Syria", continent: "Asia", capital: "Damascus", language: "Arabic", greeting: "Marhaba", greetingTranslation: "Welcome", flagEmoji: "🇸🇾", funFact: "Its capital, Damascus, is considered one of the oldest continuously inhabited cities on Earth.", characterStyle: "middle-east" },

  // T
  { name: "Tajikistan", continent: "Asia", capital: "Dushanbe", language: "Tajik", greeting: "Salom", greetingTranslation: "Peace", flagEmoji: "🇹🇯", funFact: "Over 93% of its terrain is covered by the rugged Pamir and Alay mountain ranges.", characterStyle: "central-asia" },
  { name: "Tanzania", continent: "Africa", capital: "Dodoma", language: "Swahili / English", greeting: "Habari", greetingTranslation: "What news", flagEmoji: "🇹🇿", funFact: "Mount Kilimanjaro in its northern region is the highest free-standing mountain on Earth.", characterStyle: "african" },
  { name: "Thailand", continent: "Asia", capital: "Bangkok", language: "Thai", greeting: "Sawatdee", greetingTranslation: "Blessings / Greetings", flagEmoji: "🇹🇭", funFact: "The only Southeast Asian nation that successfully avoided colonization by European empires.", characterStyle: "southeast-asia", aliases: ["siam"] },
  { name: "Timor-Leste", continent: "Asia", capital: "Dili", language: "Tetum / Portuguese", greeting: "Ola", greetingTranslation: "Hello", flagEmoji: "🇹🇱", funFact: "Its coastal reefs in the Coral Triangle exhibit some of the highest marine biodiversity found anywhere.", characterStyle: "southeast-asia", aliases: ["east timor"] },
  { name: "Togo", continent: "Africa", capital: "Lomé", language: "French", greeting: "Bonjour", greetingTranslation: "Good morning", flagEmoji: "🇹🇬", funFact: "A narrow coastal nation renowned for its vibrant artisanal fabric markets and batiks.", characterStyle: "african" },
  { name: "Tonga", continent: "Oceania", capital: "Nuku'alofa", language: "Tongan / English", greeting: "Mālō e lelei", greetingTranslation: "Good day", flagEmoji: "🇹🇴", funFact: "The only Pacific island monarchy to consistently preserve its native sovereignty through modern history.", characterStyle: "oceanian" },
  { name: "Trinidad and Tobago", continent: "North America", capital: "Port of Spain", language: "English", greeting: "How you going?", greetingTranslation: "Greetings", flagEmoji: "🇹🇹", funFact: "Invented the steelpan musical drum, forged skillfully from recycled industrial oil barrels.", characterStyle: "caribbean", aliases: ["trinidad", "tobago"] },
  { name: "Tunisia", continent: "Africa", capital: "Tunis", language: "Arabic", greeting: "As-salamu alaykum", greetingTranslation: "Peace be upon you", flagEmoji: "🇹🇳", funFact: "Home to ancient Carthage and the subterranean desert dwellings of Matmata.", characterStyle: "north-africa" },
  { name: "Turkey", continent: "Asia", capital: "Ankara", language: "Turkish", greeting: "Merhaba", greetingTranslation: "Hello", flagEmoji: "🇹🇷", funFact: "Its historic city Istanbul straddles two separate continents: Europe and Asia.", characterStyle: "middle-east", aliases: ["turkiye"] },
  { name: "Turkmenistan", continent: "Asia", capital: "Ashgabat", language: "Turkmen", greeting: "Salam", greetingTranslation: "Peace", flagEmoji: "🇹🇲", funFact: "Contains the Darvaza gas crater, an astonishing natural gas fissure flaming continuously since 1971.", characterStyle: "central-asia" },
  { name: "Tuvalu", continent: "Oceania", capital: "Funafuti", language: "Tuvaluan / English", greeting: "Talofa", greetingTranslation: "Hello", flagEmoji: "🇹🇻", funFact: "Generates notable national income by licensing its country-code top-level web domain: .tv.", characterStyle: "oceanian" },

  // U
  { name: "Uganda", continent: "Africa", capital: "Kampala", language: "English / Swahili", greeting: "Oli otya", greetingTranslation: "How are you", flagEmoji: "🇺🇬", funFact: "Sanctuary for more than half of the planet's remaining wild mountain gorillas in Bwindi.", characterStyle: "african" },
  { name: "Ukraine", continent: "Europe", capital: "Kyiv", language: "Ukrainian", greeting: "Pryvit", greetingTranslation: "Hi", flagEmoji: "🇺🇦", funFact: "Possesses vast expanses of fertile 'chornozem' black soil, serving as an international breadbasket.", characterStyle: "slavic" },
  { name: "United Arab Emirates", continent: "Asia", capital: "Abu Dhabi", language: "Arabic", greeting: "Marhaba", greetingTranslation: "Welcome", flagEmoji: "🇦🇪", funFact: "Home to the Burj Khalifa in Dubai, the tallest engineered structure built by human hands.", characterStyle: "middle-east", aliases: ["uae", "emirates"] },
  { name: "United Kingdom", continent: "Europe", capital: "London", language: "English", greeting: "Cheerio!", greetingTranslation: "Good health!", flagEmoji: "🇬🇧", funFact: "Pioneered the industrial revolution, parliamentary democracy, and the English language.", characterStyle: "celtic", aliases: ["uk", "great britain", "britain", "england", "scotland", "wales"] },
  { name: "United States", continent: "North America", capital: "Washington, D.C.", language: "English", greeting: "Howdy!", greetingTranslation: "Hello!", flagEmoji: "🇺🇸", funFact: "Established Yellowstone in 1872, the world's very first dedicated National Park.", characterStyle: "western", aliases: ["usa", "us", "america", "united states of america"] },
  { name: "Uruguay", continent: "South America", capital: "Montevideo", language: "Spanish", greeting: "¡Hola!", greetingTranslation: "Hello!", flagEmoji: "🇺🇾", funFact: "The first nation to offer a complimentary personal laptop computer to every public schoolchild.", characterStyle: "latino" },
  { name: "Uzbekistan", continent: "Asia", capital: "Tashkent", language: "Uzbek", greeting: "Salom", greetingTranslation: "Peace", flagEmoji: "🇺🇿", funFact: "Samarkand was the glittering architectural jewel of the historical overland Silk Road trade routes.", characterStyle: "central-asia" },

  // V
  { name: "Vanuatu", continent: "Oceania", capital: "Port Vila", language: "Bislama / English / French", greeting: "Halo", greetingTranslation: "Hello", flagEmoji: "🇻🇺", funFact: "The ancient tradition of 'land diving' on Pentecost Island served as the direct precursor to bungee jumping.", characterStyle: "oceanian" },
  { name: "Vatican City", continent: "Europe", capital: "Vatican City", language: "Latin / Italian", greeting: "Salve", greetingTranslation: "Greetings", flagEmoji: "🇻🇦", funFact: "The smallest independent state on Earth, containing the Sistine Chapel and St. Peter's Basilica.", characterStyle: "mediterranean", aliases: ["vatican", "holy see"] },
  { name: "Venezuela", continent: "South America", capital: "Caracas", language: "Spanish", greeting: "¡Hola!", greetingTranslation: "Hello!", flagEmoji: "🇻🇪", funFact: "Angel Falls is the highest uninterrupted waterfall on Earth, dropping a staggering 979 meters.", characterStyle: "latino" },
  { name: "Vietnam", continent: "Asia", capital: "Hanoi", language: "Vietnamese", greeting: "Xin chào", greetingTranslation: "Hello", flagEmoji: "🇻🇳", funFact: "Son Doong cave within its limestone karst preserves is so massive it has its own localized weather clouds.", characterStyle: "southeast-asia" },

  // Y
  { name: "Yemen", continent: "Asia", capital: "Sana'a", language: "Arabic", greeting: "Marhaban", greetingTranslation: "Welcome", flagEmoji: "🇾🇪", funFact: "The historic walled city of Shibam is often dubbed the 'Manhattan of the Desert' for its ancient mud skyscrapers.", characterStyle: "middle-east" },

  // Z
  { name: "Zambia", continent: "Africa", capital: "Lusaka", language: "English", greeting: "Muli bwanji", greetingTranslation: "How are you", flagEmoji: "🇿🇲", funFact: "Shares the Victoria Falls ('Mosi-oa-Tunya' or Smoke That Thunders) with neighbor Zimbabwe.", characterStyle: "african" },
  { name: "Zimbabwe", continent: "Africa", capital: "Harare", language: "Shona / Ndebele / English", greeting: "Mhoro", greetingTranslation: "Hello", flagEmoji: "🇿🇼", funFact: "Named after the historic stone enclosures of Great Zimbabwe, built by medieval ancestors without mortar.", characterStyle: "african" }
];

/**
 * Letter classification map built dynamically
 */
const DatasetService = {
  data: COUNTRY_DATASET,

  getAvailableLetters(difficulty = 'normal') {
    const lettersMap = {};
    this.data.forEach(c => {
      const char = c.name.charAt(0).toUpperCase();
      lettersMap[char] = (lettersMap[char] || 0) + 1;
    });

    const letters = Object.keys(lettersMap).sort();

    if (difficulty === 'easy') {
      // Exclude letters with fewer than 4 countries (e.g., O, Q, Y)
      return letters.filter(l => lettersMap[l] >= 4);
    }
    return letters;
  },

  getCountriesForLetter(letter) {
    const char = letter.toUpperCase();
    return this.data.filter(c => c.name.charAt(0).toUpperCase() === char);
  },

  findCountry(input) {
    const clean = Utils.normalize(input);
    if (!clean) return null;

    return this.data.find(c => {
      // Match official title
      if (Utils.normalize(c.name) === clean) return true;
      // Match recognized aliases
      if (c.aliases && c.aliases.some(alias => Utils.normalize(alias) === clean)) {
        return true;
      }
      return false;
    }) || null;
  }
};